name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # 1. Checka ut koden
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      # 4. Run code formatting check (black/flake8)
      - name: Run code formatting check
        run: |
          pip install black 
          black --check .
          

      # 5. Run unit tests
      - name: Run unit tests
        run: |
          pytest -v --maxfail=1 --disable-warnings

      # 6. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t tspec:test .
